name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Installing jest
        run: npm install --save-dev jest ts-jest typescript ts-node

      - name: Test suit run
        run: npm run test

      - name: Install serverless framework
        run: npm install -g serverless

      - name: AWS Credentials configure
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install NPM dependecies
        run: npm install

      - name: Serverless deploy
        run: serverless deploy --verbose
